name: 'Tg Notifier About new pull request'
inputs:
  chat:
    description: 'Chat to send: chat id or @channel_name'
    required: true
  token:
    description: 'Telegram Bot token'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  repositoryName:
    description: 'Repository name'
    default: ${{ github.repository.name }}
  repositoryName:
    description: 'Repository name'
    default: ${{ github.repository_owner }}
  prAuthor:
    description: 'Pr author'
    default: ${{ github.event.pull_request.user.login }}
  prNumber:  
    description: 'Pr number'
    default: ${{ github.event.number }}
  prTitle: 
    description: 'Pr title'
    default: ${{ github.event.pull_request.title }}
  prBody: 
    description: 'Pr body'
    default: ${{ github.event.pull_request.body }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'repeat'
  color: 'green'
